spring.application.name=gestionacademica
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=4184812
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=colegiosanmarino43@gmail.com
spring.mail.password=ujol ptph eyrw vfkg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
institucion.nombre=Colegio San Marino
institucion.direccion=Cra 7 No. 40-53
institucion.telefono=+57 (1) 123-4567
institucion.correo=colegiosanmarino43@gmail.com